### ISSUE TITLE
Shebang

### ISSUE THREAD

**Issue by virgilwashere** [felippe-regazio/sh-simple-deployer#1]
As you are using bash `[[  ]]` why not make your shell interpreter `#!/usr/bin/env bash`, instead of _bash in sh mode_ with `/bin/sh`?

**Comment by felippe-regazio** [comment]
To tell you the truth, i googled about the `#!/usr/bin/env bash` to discover what it really does. Sorry about my knowledge lack haha. But i came to a question: its true that env will be always located at `/usr/bin/env`? In you experience, that should be a concern? If so, would be possible to use `type env` on the Shebang to point the env path?

**Comment by virgilwashere** [comment]
`/usr/bin/env` is part of 🖥 GNU `coreutils` so I'd say it's fairly safe.

```console
$ type -P env
/usr/bin/env

$ env --version
env (GNU coreutils) 8.28
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard Mlynarik and David MacKenzie.
```

Also: http://mywiki.wooledge.org/BashGuide/CommandsAndArguments#Scripts

> Tip — Instead of `#!/bin/bash`, you could use
>
> `#!/usr/bin/env bash`
>
> `env` searches `$PATH` for the executable named by its first argument (in this case, `bash`). 
>
> **Please** do not be fooled by scripts or examples on the Internet that use `#!/bin/sh` as the interpreter. `sh` is not `bash`! Bash itself is a "sh-compatible" shell (meaning that it can run most `sh` scripts and carries much of the same syntax) however, the opposite is not true; some features of Bash will break or cause unexpected behaviour in `sh`.

A real use case - any 🍎MacOS system that has upgraded `bash` via 🍺`homebrew`

And for your further 🎓education 😉 

```bash
# "unofficial" bash strict mode
# See: http://redsymbol.net/articles/unofficial-bash-strict-mode
set -o errexit  # Exit when simple command fails               'set -e'
set -o errtrace # Exit on error inside any functions or subshells.
set -o nounset  # Trigger error when expanding unset variables 'set -u'
set -o pipefail # Do not hide errors within pipes              'set -o pipefail'
# set -o xtrace # Trace the execution of the script (debug)    'set -x'
IFS=$'\n\t'     # Split words on \n\t rather than spaces
```


Virgil

**Comment by felippe-regazio** [comment]
Uow Virgil, thanks for patience and time to explain me that. I updated the #shebang on the sh files based on your appointments. Thanks again, and have a nice day!

**Comment by felippe-regazio** [comment]
Uow, thanks for your time and patience to explain me that. I really appreciated. 
Anyway, when i change the deploy.sh #shebang from sh to `#!/usr/bin/env sh`, the output becomes pretty different. With `#!/bin/sh` the colors and \n are preserved, but with `#!/usr/bin/env bash` they are not, all the output becomes raw text. With `#!/usr/bin/env sh` it goes well too. Im thinking if i have to refactor the way the script is outputting information (strings).

**Comment by felippe-regazio** [comment]
Update: I changed the Shebang in according to your suggestion. Commited. 
Also i replaced `echos` to `printf`. One last doubt:

Is `\n` inside strings fully compatible with printf?
Do you think the script is finally portable using the new shebang and printf?

**Comment by virgilwashere** [comment]
> Also I replaced `echos` to `printf`. One last doubt:
👍 
> Is `\n` inside strings fully compatible with printf?
✔️ 
But! you need to tell `printf` that it's a _binary_ variable:

 🎨 `blue` and `nc` _(no colour)_

```bash
printf 'logfile: %b%s%b\n' "$blue" "$logfile" "$nc" >&2
```

And this is part of my 🌈 colour library I source:

```bash
# Reset
  export   nc="\e[0m"              # "no colour"

  export   black="\e[0;30m"        # black
  export     red="\e[0;31m"        # red
  export   green="\e[0;32m"        # green
  export  yellow="\e[38;5;226m"    # yellow 256
  export    blue="\e[0;34m"        # blue
  export  purple="\e[0;35m"        # purple
  export    cyan="\e[0;36m"        # cyan
  export    grey="\e[0;37m"        # light grey
  export   white="\e[1;37m"        # white
  export   ltred="\e[1;31m"        # light red
  export ltgreen="\e[1;32m"        # light green
  export  orange="\e[38;5;208m"    # orange 256
...
# vim: tabstop=2 shiftwidth=2 expandtab filetype=md syntax=sh

```

🌐 https://misc.flogisoft.com/bash/tip_colors_and_formatting is an excellent place to start if you want to play with colour in the terminal.

Virgil

**Comment by felippe-regazio** [comment]
Nice, so thats it. Ill update the colour scheme, also closing this issue.
Many thanks for your time, contribution and patience!

See ya ; )

**Comment by felippe-regazio** [comment]
Nice! I updated the colour scheme based on your personal snippet.
Many thanks for your appointments and patience, you contributed a lot with the script and with my education. I added a footnote on this script readme giving some credits.

Closing the issue.
Have a nice day!

**Comment by felippe-regazio** [comment]
Nice! I updated the colour scheme based on your personal snippet.
Many thanks for your appointments and patience, you contributed a lot with the script and with my education. I added a footnote on this script readme giving you the credits.

**Comment by felippe-regazio** [comment]
Closing issue.
